version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/ax-i-om/rapture/web"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["jquery"]